### ISSUE TITLE
Release 0.1.1 Is not showing up on in atom's plugin manager

### ISSUE THREAD

**Issue by aaaronic** [Pangoraw/git-hide#1]
Is it because you named it `0.1.1` instead of `v0.1.1` (you named `v0.1.0` with the "v")?

**Comment by Pangoraw** [comment]
Do you mean in the version field of `package.json`, I should write `v0.1.1` ?

**Comment by Pangoraw** [comment]
Ok, I edited the tag in the Github release, should do it.

**Comment by aaaronic** [comment]
I think the issue actually lies in your not using [apm](https://atom.io/docs/v0.60.0/publishing-a-package) to publish the update to the package -- usually done with something like `apm publish <new version number>`, which bumps the version number for you, creates the git tag, updates GitHub, and updates Atom's registry.

At this point, since you've already edited the package file, created the git tag, and it's present on GitHub, all I think you need to do is tell Atom to update your package based on that tag's existence:

```
apm publish --tag v0.1.1
```

**Comment by Pangoraw** [comment]
Actually that was what had to be done ! Thanks you very much for your help ! Package is now up to date --> https://atom.io/packages/git-hide

**Comment by aaaronic** [comment]
Happy I could help. Thanks for the plugin!
