### ISSUE TITLE
Seems to be broken on Atom 1.6.0

### ISSUE THREAD

**Issue by lordmat0** [Pangoraw/git-hide#4]
Very useful plugin, so thanks for that :)

This doesn't seem to be working on Atom 1.6.0. which was released 7 days ago.

**Comment by lordmat0** [comment]
Reseting atom fixed the issue.

**Comment by corysimmons** [comment]
Seems broken in 1.8 now.

**Comment by Pangoraw** [comment]
Yes, this is due to issue [#869](https://github.com/atom/tree-view/issues/869) of the tree-view plugin.

**Comment by corysimmons** [comment]
Thanks for the update. Care to ping this issue when this gets fixed?
